project_id = "xtessaulbiqosjyykfse"

[functions.weekly-report]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.vercel-analytics]
verify_jwt = true

[functions.enrich-lead]
verify_jwt = false
